Repository Rohit-554/Peer-Hacktoberfest, pull requests merged in 2025-10, with the labels that each got.

#7 [Feat : Added QR code generation feature]
  package-lock.json
  src/pages/App.jsx
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2025

#9 [Feat: Added Chat Feature]
  src/pages/App.jsx
Labels: hacktoberfest-accepted, hacktoberfest-2025

#10 feat: Add PWA support with installable app and offline capabilities
  PWA_INSTALLATION.md
  README.md
  generate-icons.html
  index.html
  package.json
  public/apple-touch-icon.png
  public/browserconfig.xml
  public/favicon-16x16.png
  public/favicon-32x32.png
  public/favicon.ico
  public/manifest.json
  public/mstile-150x150.png
  public/offline.html
  public/pwa-192x192.png
  public/pwa-512x512.png
  src/main.jsx
  vite.config.js
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2025

#19 P2p/dev server #1
  HTTPS_SETUP.md
  certs/.gitkeep
  package.json
  scripts/generate-cert.js
  vite.config.js
Labels: hacktoberfest-accepted, hacktoberfest-2025

#21 fixed build issue
  package.json
Labels: hacktoberfest-2025

#22 Feature/peer status
  dev-dist/sw.js
  src/components/StatusSelector.jsx
  src/pages/App.jsx
  src/styles.css
  vite.config.js
Labels: hacktoberfest-accepted, hacktoberfest-2025

#23 Add screen sharing functionality: start/stop share, display remote sc…
  src/pages/App.jsx
Labels: hacktoberfest-accepted, hacktoberfest-2025
